export const MutationKey = {
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  VERIFY_EMAIL: "VERIFY_EMAIL",
  SEND_OTP: "SEND_OTP",
  LOGOUT: "LOGOUT",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",
  UPDATE_USER: "UPDATE_USER",
  RESET_PASSWORD_EMAIL: "RESET_PASSWORD_EMAIL",
  RESET_PASSWORD_OTP: "RESET_PASSWORD_OTP",
  RESET_PASSWORD_NEW_PASSWORD: "RESET_PASSWORD_NEW_PASSWORD",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
} as const;
