export const MutationKey = {
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  VERIFY_EMAIL: "VERIFY_EMAIL",
  SEND_OTP: "SEND_OTP",
  LOGOUT: "LOGOUT",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",
  UPDATE_USER: "UPDATE_USER",
} as const;
