export const QueryKey = {
  CURRENT_USER: "CURRENT_USER",
  DISCOVER_MOVIES: "DISCOVER_MOVIES",
  MOVIE: "MOVIE",
  FILE: "FILE",
  LISTS: "LISTS",
  ANALYTICS: "ANALYTICS",
  GENRE_STATS: "GENRE_STATS",
  PERSON_STATS: "PERSON_STATS",
} as const;
